name: Build and Upload OpenCV Artifacts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        opencv-version: ['4.11.0']
      fail-fast: false

    steps:
    # Debug: Print environment
    - name: Debug Info
      run: |
        echo "Runner OS: ${{ matrix.os }}"
        echo "OpenCV Version: ${{ matrix.opencv-version }}"
        echo "Event: ${{ github.event_name }}"
        echo "Branch: ${{ github.ref_name }}"

    # Checkout the repository
    - uses: actions/checkout@v4

    # Cache OpenCV
    - name: Cache OpenCV
      id: cache-opencv
      uses: actions/cache@v4
      with:
        path: |
          ./opencv-install
          ${{ runner.os == 'Windows' && 'C:/opencv-install' || '' }}
        key: ${{ runner.os }}-opencv-${{ matrix.opencv-version }}

    # Install OpenCV on Linux (Manual Setup)
    - name: Setup OpenCV (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        # Update package lists and install dependencies
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          git \
          libgtk2.0-dev \
          pkg-config \
          libavcodec-dev \
          libavformat-dev \
          libswscale-dev \
          libtbb2 \
          libtbb-dev \
          libjpeg-dev \
          libpng-dev \
          libtiff-dev \
          libdc1394-dev
        # Clone OpenCV and opencv_contrib
        mkdir -p opencv-install
        cd opencv-install
        git clone --depth 1 --branch ${{ matrix.opencv-version }} https://github.com/opencv/opencv.git
        git clone --depth 1 --branch ${{ matrix.opencv-version }} https://github.com/opencv/opencv_contrib.git
        # Build and install OpenCV
        mkdir -p build
        cd build
        cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_EXAMPLES=OFF \
          -DBUILD_TESTS=OFF \
          -DBUILD_PERF_TESTS=OFF \
          -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules \
          -DCMAKE_INSTALL_PREFIX=/usr/local \
          ../opencv
        make -j$(nproc)
        sudo make install
        cd ../..

    # Install OpenCV on Windows with MSVC 2022
    - name: Setup OpenCV (Windows)
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        echo "Starting Windows build"
        mkdir opencv-install
        cd opencv-install
        git clone --depth 1 --branch ${{ matrix.opencv-version }} https://github.com/opencv/opencv.git
        git clone --depth 1 --branch ${{ matrix.opencv-version }} https://github.com/opencv/opencv_contrib.git
        mkdir build
        cd build
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cmake -G "Visual Studio 17 2022" -A x64 ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DBUILD_EXAMPLES=OFF ^
          -DBUILD_TESTS=OFF ^
          -DBUILD_PERF_TESTS=OFF ^
          -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules ^
          -DCMAKE_INSTALL_PREFIX=../install ^
          ../opencv
        msbuild INSTALL.vcxproj /p:Configuration=Release /m
        cd ../..
        move opencv-install\install C:\opencv-install

    # Set environment variables for OpenCV
    - name: Set OpenCV Environment Variables
      shell: bash
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          echo "OpenCV_DIR=/usr/local/lib/cmake/opencv4" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        else
          echo "OpenCV_DIR=C:/opencv-install/lib/cmake/opencv4" >> $GITHUB_ENV
          echo "PATH=C:/opencv-install/bin;$PATH" >> $GITHUB_ENV
        fi

    # Verify OpenCV installation
    - name: Verify OpenCV Installation
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          pkg-config --modversion opencv4
        else
          dir C:\opencv-install\bin
        fi

    # Package and Upload
    - name: Package OpenCV Artifacts
      shell: bash
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          tar -czf opencv-${{ matrix.opencv-version }}-linux.tar.gz -C /usr/local .
        else
          powershell -command "Compress-Archive -Path C:/opencv-install/* -DestinationPath opencv-${{ matrix.opencv-version }}-windows.zip"
        fi
    - name: Upload OpenCV Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: opencv-${{ matrix.opencv-version }}-${{ matrix.os }}
        path: |
          opencv-${{ matrix.opencv-version }}-*.tar.gz
          opencv-${{ matrix.opencv-version }}-*.zip
        retention-days: 7